apiVersion: v1 
kind: Service 
metadata: 
 name: mongodb-service 
spec: 
 type: LoadBalancer 
 ports: 
 - port: 27017 
 selector: 
  app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # creationTimestamp: null
  # labels:
  #   app: mongodb-deployment
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo
        name: mongo
        env:
        - name: mongo_INITDB_ROOT_USERNAME
          value: 'dummy'
        - name: mongo_INITDB_ROOT_PASSWORD
          value: 'dummy'