apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: LoadBalancer
  ports:
    - port: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo
          name: mongodb
          env:
            - name: MONGO_ROOT_PASSWORD
              value: password
            - name: MONGO_USER
              value: user
            - name: MONGO_PASSWORD
              value: sofe4790u
            - name: MONGO_DATABASE
              value: MongoDB
          ports:
            - containerPort: 27017
              name: mongodb
